version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443

  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secure

  php-fpm:
    image: php:latest

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
